version: '3.8'

services:
  # mysql:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: testdb
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
  #   ports:
  #     - "8083:80"
  #   depends_on:
  #     - mysql
  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   healthcheck:
  #     test: ["CMD", "mongo", "--eval", "db.stats()"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  # mongo-express:
  #   image: mongo-express:latest
  #   restart: always
  #   container_name: mongo_express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  #   depends_on:
  #     - mongo

  # influxdb:
  #   image: influxdb:2.7
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - DOCKER_INFLUXDB_INIT_MODE=setup
  #     - DOCKER_INFLUXDB_INIT_USERNAME=admin
  #     - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
  #     - DOCKER_INFLUXDB_INIT_ORG=myorg
  #     - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
  #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.enrollment.enabled=false
  #     - network.host=0.0.0.0
  #     - node.name=es01
  #   ports:
  #     - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.2
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./examples/provider/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
